#!/bin/bash

kubectl get pod | grep explorer | cut -d' ' -f1 | xargs kubectl delete pod
kubectl get pvc | grep explorer | cut -d' ' -f1 | xargs kubectl delete pvc
kubectl delete service node-endpoint explorer
kubectl delete deployment explorer
