#!/bin/bash

kubectl get deployment | grep node | cut -d' ' -f1 | xargs kubectl delete deployment
kubectl get pod | grep node | cut -d' ' -f1 | xargs kubectl delete pod
kubectl get pvc | grep node | cut -d' ' -f1 | xargs kubectl delete pvc
for n in {1..3}
do
  kubectl delete service node-$n
done
kubectl delete service node-endpoint
