#!/bin/bash

USAGE=$(cat <<EOF
Delete given resource.
Usage:
      ./delete consortium | explorer | all
Example:
      ./delete consortium
EOF
)

case $1 in
	consortium)
    kubectl get deployment | grep node | cut -d' ' -f1 | xargs kubectl delete deployment
    kubectl get pod | grep node | cut -d' ' -f1 | xargs kubectl delete pod
    kubectl get pvc | grep node | cut -d' ' -f1 | xargs kubectl delete pvc
    for n in {1..3}
    do
      kubectl delete service node-$n
    done
    kubectl delete service node-endpoint
		;;
	explorer)
    kubectl delete deployment explorer
    kubectl get pod | grep explorer | cut -d' ' -f1 | xargs kubectl delete pod
    kubectl get pvc | grep explorer | cut -d' ' -f1 | xargs kubectl delete pvc
    kubectl delete service explorer
		;;
  all)
    kubectl delete pod,pvc,deployment,service --all
    ;;
	*)
    echo "$USAGE"
		;;
esac
