#!/bin/bash

USAGE=$(cat <<EOF
Update permissioned-nodes.json file of specific node.
Usage:
      ./kcp <file> node-1 | node-2 | node-3
Example:
      ./kcp ./permissioned-nodes.json node-1
EOF
)

if [ $# -ne 2 ] || [[ $2 != "node-1" ]] && [[ $2 != "node-2" ]] && [[ $2 != "node-3" ]]
then
  echo "$USAGE"
  exit 0
fi

pod=`kubectl get pod | grep $2 | cut -d' ' -f1`
file=/qdata/dd/permissioned-nodes.json
kubectl cp $1 $pod:$file
