#!/bin/bash

USAGE=$(cat <<EOF
Recreate given resource.
Usage:
      ./recreate consortium | explorer | all
Example:
      ./recreate consortium
EOF
)

case $1 in
	consortium)
    ./delete consortium
    ./create consortium
		;;
	explorer)
    ./delete explorer
    ./create explorer
		;;
  all)
    ./delete all
    ./create all
    ;;
	*)
    echo "$USAGE"
		;;
esac
